# Generated by Django 3.0.13 on 2021-08-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name_plural': 'Tracking'},
        ),
    ]
