# Generated by Django 3.0.13 on 2021-08-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210803_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='location_id',
            field=models.IntegerField(default=123456789, max_length=40),
        ),
    ]
