# Generated by Django 3.0.13 on 2021-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_tracking_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='tracking_urls',
            field=models.URLField(default='http://www.correios.com.br/rastreamento'),
        ),
    ]
